In [2]:
import numpy as np

In [3]:
# Creating 1D array
arr_1d = np.array([1, 2, 3])

# Creating 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Creating 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [4]:
# Array Shape and Reshaping
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Shape
shape = arr.shape
print(shape)

# Reshaping
reshaped_arr = arr.reshape((3, 2))

(2, 3)


In [5]:
# Random Module in NumPy
random_array = np.random.rand(3, 3)  # 3x3 array of random values between 0 and 1
print(random_array)

[[0.06482534 0.68076252 0.38018597]
 [0.95233462 0.44024693 0.13840988]
 [0.8937085  0.44726015 0.0559222 ]]


In [6]:
random_int = np.random.randint(1, 10)  # Random integer between 1 and 10
print(random_int)

7


In [7]:
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Performing mathematical and statistical operations
mean_value = np.mean(arr)  # Calculating the mean
median_value = np.median(arr)  # Calculating the median
std_deviation = np.std(arr)  # Calculating the standard deviation
min_value = np.min(arr)  # Finding the minimum value
max_value = np.max(arr)  # Finding the maximum value

In [8]:
# Generating random standard normal matrices
a = np.random.standard_normal((2, 3))
b = np.random.standard_normal((2, 3))

# Vertically stacking matrices 'a' and 'b' using vstack
v = np.vstack([a, b])

# Horizontally stacking matrices 'a' and 'b' using hstack
h = np.hstack([a, b])

In [15]:
# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Printing the original array
print("\nOriginal Array:")
print(arr)
# Transposing the array using the transpose method
transposed_arr = arr.transpose()

# Printing the transposed array
print("\nTransposed Array:")
print(transposed_arr)


Original Array:
[[1 2 3]
 [4 5 6]]

Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


In [17]:
# Creating a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Accessing individual elements by index
print("First element:", arr_1d[0])
print("Third element:", arr_1d[2])

# Slicing to extract a subset of the array
subset_array = arr_1d[1:4]
print("Subset array:", subset_array)

First element: 1
Third element: 3
Subset array: [2 3 4]


In [18]:
# Modifying array elements through indexing
arr_1d[2] = 10
print("Modified array:", arr_1d)

Modified array: [ 1  2 10  4  5]


In [19]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing individual elements in a 2D array
element_2_3 = arr_2d[1, 2]
print("Element at (1, 2):", element_2_3)

# Slicing rows and columns in a 2D array
second_row = arr_2d[1, :]
first_column = arr_2d[:, 0]
print("Second row:", second_row)
print("First column:", first_column)

Element at (1, 2): 6
Second row: [4 5 6]
First column: [1 4 7]


In [ ]:
# Conditional indexing
greater_than_5 = arr_2d[arr_2d > 5]
print("Elements greater than 5:", greater_than_5)

In [ ]:
# Create a sample array representing daily temperatures
temperature_data = np.array([[22, 28, 24, 30, 20],
                             [26, 23, 27, 22, 29],
                             [18, 21, 26, 28, 25],
                             [30, 31, 20, 22, 27]])

In [20]:
# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Saving the array to a file named 'array.npy'
np.save('array.npy', arr)

# Loading the array from the saved file
loaded_arr = np.load('array.npy')